# Generated by Django 5.0.3 on 2026-04-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='File gambar bukti transfer atau pembayaran yang diunggah tenant.', upload_to='payments/%Y/%m/%d/', verbose_name='Gambar Bukti Pembayaran')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat bukti pembayaran diunggah ke sistem.', verbose_name='Diunggah Pada')),
            ],
            options={
                'verbose_name': 'Bukti Pembayaran',
                'verbose_name_plural': 'Bukti Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Tanggal mulai masa sewa yang diajukan tenant.', verbose_name='Tanggal Mulai Sewa')),
                ('duration_months', models.PositiveIntegerField(default=1, help_text='Lama sewa dalam satuan bulan.', verbose_name='Durasi Sewa (Bulan)')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Total biaya booking yang dihitung otomatis berdasarkan harga kamar dan durasi sewa.', max_digits=12, verbose_name='Total Harga')),
                ('status', models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('waiting_verification', 'Menunggu Verifikasi'), ('paid', 'Lunas'), ('rejected', 'Ditolak')], default='pending_payment', help_text='Status transaksi booking: menunggu pembayaran, verifikasi, lunas, atau ditolak.', max_length=25, verbose_name='Status Booking')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat booking pertama kali dibuat.', verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Waktu terakhir data booking diperbarui.', verbose_name='Diperbarui Pada')),
                ('room', models.ForeignKey(help_text='Kamar yang dipesan dalam transaksi ini.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='kosts.room', verbose_name='Kamar')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Daftar Booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
