# Generated by Django 5.0.3 on 2026-04-15 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(help_text='Pengguna tenant yang melakukan pemesanan kamar.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='booking',
            field=models.OneToOneField(help_text='Booking yang terkait dengan bukti pembayaran ini.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='transactions.booking', verbose_name='Booking'),
        ),
    ]
