# Generated by Django 5.0.3 on 2026-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama properti kost yang akan ditampilkan kepada calon tenant.', max_length=255, verbose_name='Nama Kost')),
                ('address', models.TextField(help_text='Alamat lengkap kost agar mudah ditemukan oleh tenant dan admin.', verbose_name='Alamat')),
                ('description', models.TextField(help_text='Ringkasan kondisi, keunggulan, dan informasi penting mengenai kost.', verbose_name='Deskripsi')),
                ('facilities', models.TextField(help_text='Daftar fasilitas kost. Pisahkan dengan koma, misalnya: WiFi, AC, Kamar Mandi Dalam.', verbose_name='Fasilitas')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Koordinat lintang lokasi kost. Opsional, digunakan untuk kebutuhan pemetaan.', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Koordinat bujur lokasi kost. Opsional, digunakan untuk kebutuhan pemetaan.', max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat data kost pertama kali dibuat.', verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Waktu terakhir data kost diperbarui.', verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Kost',
                'verbose_name_plural': 'Daftar Kost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='File gambar utama atau pendukung yang menampilkan kondisi kost.', upload_to='kosts/%Y/%m/%d/', verbose_name='Gambar Kost')),
                ('caption', models.CharField(blank=True, help_text='Keterangan singkat untuk membantu admin atau owner mengenali isi gambar.', max_length=255, verbose_name='Keterangan Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat gambar kost pertama kali diunggah.', verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Gambar Kost',
                'verbose_name_plural': 'Galeri Gambar Kost',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Nomor atau kode unik kamar dalam satu kost.', max_length=50, verbose_name='Nomor Kamar')),
                ('price', models.DecimalField(decimal_places=2, help_text='Harga sewa kamar per bulan sesuai penawaran owner.', max_digits=10, verbose_name='Harga per Bulan')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('booked', 'Dipesan'), ('occupied', 'Dihuni')], default='available', help_text='Status operasional kamar: tersedia, dipesan, atau sudah dihuni.', max_length=15, verbose_name='Status Kamar')),
                ('description', models.TextField(blank=True, help_text='Catatan tambahan mengenai ukuran, fasilitas, atau kondisi kamar.', null=True, verbose_name='Deskripsi Kamar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat data kamar pertama kali dibuat.', verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Kamar',
                'verbose_name_plural': 'Daftar Kamar',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='File gambar yang menampilkan kondisi aktual kamar.', upload_to='rooms/%Y/%m/%d/', verbose_name='Gambar Kamar')),
                ('caption', models.CharField(blank=True, help_text='Keterangan singkat untuk membantu admin, owner, atau tenant memahami isi gambar.', max_length=255, verbose_name='Keterangan Gambar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Waktu saat gambar kamar pertama kali diunggah.', verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Gambar Kamar',
                'verbose_name_plural': 'Galeri Gambar Kamar',
                'ordering': ['created_at'],
            },
        ),
    ]
