# Generated by Django 5.0.3 on 2026-04-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kost',
            name='owner',
            field=models.ForeignKey(help_text='Pengguna owner yang bertanggung jawab atas data kost ini.', on_delete=django.db.models.deletion.CASCADE, related_name='kosts', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Kost'),
        ),
        migrations.AddField(
            model_name='kostimage',
            name='kost',
            field=models.ForeignKey(help_text='Kost yang memiliki gambar ini.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kosts.kost', verbose_name='Kost'),
        ),
        migrations.AddField(
            model_name='room',
            name='kost',
            field=models.ForeignKey(help_text='Kost induk tempat kamar ini terdaftar.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='kosts.kost', verbose_name='Kost'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(help_text='Kamar yang memiliki gambar ini.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kosts.room', verbose_name='Kamar'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('kost', 'room_number')},
        ),
    ]
